name: ci
on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: python -m pip install -r python/requirements.txt
      - name: Format
        run: python -m black ./python --config python/black.toml --check --verbose
      - name: Type check
        run: cd python && python -m mypy edgin_around_api/*.py test/test_*.py

  test:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: python -m pip install -r python/requirements.txt
      - name: Test
        run: cd python && python -m unittest

  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Package
        run: cd python && python setup.py sdist
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: python/dist/edgin_around_api-*.tar.gz


